// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcwpdopefazjdzhnglbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjd3Bkb3BlZmF6amR6aG5nbGJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MjEyMzcsImV4cCI6MjA2NzQ5NzIzN30.0EBiWSvdWk9LuCq0yDOFE2f7_lX9D7LfXyocBv0nHfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});